name: Automatic CI for Utility Modules

on:
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  terraform_format:

    name: Run terraform fmt
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: hashicorp/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        persist-credentials: false

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.7

    - name: Format all .tf files recursively
      run: |
        terraform fmt -check -diff -recursive ${{ github.workspace }}

  terraform_lint:

    name: Run terraform-lint
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: hashicorp/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        persist-credentials: false

    - name: Setup Terraform Lint
      uses: hashicorp/setup-tflint@v1
      with:
        tflint_version: v0.26.0

    - name: Lint modules directory in a loop
      run: |
        for m in $(ls -1d modules/*/)
        do
          tflint \
            --config ${{ github.workspace }}/.tflint.hcl \
            ${{ github.workspace }}/${m}
        done

    - name: Lint fixtures directory in a loop
      run: |
        for m in $(ls -1d fixtures/*/)
        do
          tflint \
            --config ${{ github.workspace }}/.tflint.hcl \
            ${{ github.workspace }}/${m}
        done
