name: Create Jira Issue

on:
  issues:
    types: [opened, closed, deleted, reopened]
  pull_request_target:
    types: [opened, closed, reopened]
  issue_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      project:
        required: true
        type: string
      github-team:
        required: true
        type: string
        default: Terraform-Enterprise

jobs:
  call-workflow:
    uses: ./.github/workflows/create-jira-issue.yml
  with:
    github-team: ${{ inputs.github-team }}
    project: ${{ inputs.project }}
  secrets:
    JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
    JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
    JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
