name: Pull Request Test Handler

on:
  repository_dispatch:
    types:
      - test-command

jobs:
  aws_standalone_vault:
    name: Run tf-test on AWS Standalone Vault
    if: ${{ contains(github.event.client_payload.slash_command.args.unnamed.all, 'all') || contains(github.event.client_payload.slash_command.args.unnamed.all, 'aws-standalone-vault') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    env:
      WORK_DIR_PATH: ./tests/aws-standalone-vault
      K6_WORK_DIR_PATH: ./tests/tfe-load-test
      AWS_DEFAULT_REGION: us-east-2
    steps:
      - name: Create URL to the run output
        id: vars
        run: echo ::set-output name=run-url::https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID

      # Checkout the branch of the AWS TFE module to be used to test changes
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ${{ env.WORK_DIR_PATH }}
          repository: hashicorp/terraform-aws-terraform-enterprise

      - name: Set Terraform Backend to TFC Workspace
        working-directory: ${{ env.WORK_DIR_PATH }}
        run: |
          sed --in-place 's/terraform {/terraform {\n\
            backend "remote" {\n\
              organization = "terraform-enterprise-modules-test"\n\
              workspaces {\n\
                name = "aws-standalone-vault"\n\
              }\n\
            }\n/' versions.tf

      - name: Set Terraform Utility Module Sources
        working-directory: ${{ env.WORK_DIR_PATH }}
        env:
          SHA: ${{ github.event.client_payload.pull_request.head.sha }}
        run: |
          sed --in-place "s/?ref=main/?ref=$SHA/" main.tf
          sed --in-place "s/?ref=main/?ref=$SHA/" tests/standalone-vault/main.tf

      # Checkout the hashicorp/tfe-load-test repository
      - name: Checkout TFE Load Test
        uses: actions/checkout@v2
        with:
          path: ${{ env.K6_WORK_DIR_PATH }}
          repository: hashicorp/tfe-load-test
          token: ${{ secrets.GH_TFE_LOAD_TEST_TOKEN }}
          persist-credentials: false

      - name: Install required tools
        working-directory: ${{ env.K6_WORK_DIR_PATH }}
        env:
          K6_URL: https://github.com/loadimpact/k6/releases/download/v0.31.1/k6-v0.31.1-linux64.tar.gz
        run: |
          sudo apt-get install jq
          curl -L $K6_URL | tar -xz --strip-components=1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_hostname: 'app.terraform.io'
          cli_config_credentials_token: ${{ secrets.AWS_STANDALONE_VAULT_TFC_TOKEN }}
          terraform_version: 1.1.5
          terraform_wrapper: true

      # Run Terraform commands between these comments vvv

      - name: Terraform Init
        id: init
        working-directory: ${{ env.WORK_DIR_PATH }}
        run: terraform init -input=false -no-color

      - name: Terraform Validate
        id: validate
        working-directory: ${{ env.WORK_DIR_PATH }}
        run: terraform validate -no-color

      - name: Write GitHub Actions runner CIDR to Terraform Variables
        working-directory: ${{ env.WORK_DIR_PATH }}
        run: |
          echo "iact_subnet_list = [\"$( dig +short @resolver1.opendns.com myip.opendns.com )/32\"]" > github.auto.tfvars

      - name: Terraform Apply HCP Vault
        id: first-apply
        working-directory: ${{ env.WORK_DIR_PATH }}
        run: terraform apply -target=module.hcp_vault.hcp_vault_cluster.test -target=module.hcp_vault.hcp_vault_cluster_admin_token.test -auto-approve -input=false -no-color 

      - name: Terraform Apply
        id: apply
        working-directory: ${{ env.WORK_DIR_PATH }}
        run: terraform apply -auto-approve -input=false -no-color

      - name: Retrieve Health Check URL
        id: retrieve-health-check-url
        working-directory: ${{ env.WORK_DIR_PATH }}
        run: |
          terraform output -no-color -raw ptfe_health_check

      - name: Wait For TFE
        id: wait-for-tfe
        timeout-minutes: 15
        env:
          HEALTH_CHECK_URL: ${{ steps.retrieve-health-check-url.outputs.stdout }}
        run: |
          echo "Curling \`health_check_url\` for a return status of 200..."
          while ! curl -sfS --max-time 5 "$HEALTH_CHECK_URL"; do sleep 5; done

      - name: Retrieve TFE URL
        id: retrieve-tfe-url
        working-directory: ${{ env.WORK_DIR_PATH }}
        run: |
          terraform output -no-color -raw ptfe_endpoint

      - name: Retrieve IACT
        id: retrieve-iact
        env:
          IACT_URL: "${{ steps.retrieve-tfe-url.outputs.stdout }}/admin/retrieve-iact"
        run: |
          token=$(curl --fail --retry 5 --verbose "$IACT_URL")
          echo "::set-output name=token::$token"

      - name: Create Admin in TFE
        id: create-admin
        env:
          TFE_PASSWORD: ${{ secrets.TFE_PASSWORD }}
          IAU_URL: "${{ steps.retrieve-tfe-url.outputs.stdout }}/admin/initial-admin-user"
          IACT: ${{ steps.retrieve-iact.outputs.token }}
        run: |
          echo \
            '{"username": "test", "email": "team-tf-enterprise@hashicorp.com", "password": "$TFE_PASSWORD"}' \
            > ./payload.json
          response=$( \
            curl \
            --fail \
            --retry 5 \
            --verbose \
            --header 'Content-Type: application/json' \
            --data @./payload.json \
            "$IAU_URL"?token="$IACT")
          echo "::set-output name=response::$response"

      - name: Retrieve Admin Token
        id: retrieve-admin-token
        env:
          RESPONSE: ${{ steps.create-admin.outputs.response }}
        run: |
          token=$(echo "$RESPONSE" | jq --raw-output '.token')
          echo "::set-output name=token::$token"

      - name: Run k6 Smoke Test
        id: run-smoke-test
        working-directory: ${{ env.K6_WORK_DIR_PATH }}
        env:
          K6_PATHNAME: "./k6"
          TFE_URL: "${{ steps.retrieve-tfe-url.outputs.stdout }}"
          TFE_API_TOKEN: "${{ steps.retrieve-admin-token.outputs.token }}"
          TFE_EMAIL: team-tf-enterprise@hashicorp.com
        run: |
          make smoke-test

      - name: Terraform Destroy
        id: destroy
        if: ${{ always() && github.event.client_payload.slash_command.args.named.destroy != 'false' }}
        working-directory: ${{ env.WORK_DIR_PATH }}
        run: terraform destroy -auto-approve -input=false -no-color

      # Run Terraform commands between these comments ^^^

      - name: Update comment
        if: ${{ always() }}
        uses: peter-evans/create-or-update-comment@c9fcb64660bc90ec1cc535646af190c992007c32
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          body: |
            ${{ format('### {0} Terraform AWS Standalone Vault Test Report', job.status == 'success' && ':white_check_mark:' || ':x:') }}

            ${{ format(':link: [Action Summary Page]({0})', steps.vars.outputs.run-url) }}

            ${{ format('- {0} Terraform Init', steps.init.outcome == 'success' && ':white_check_mark:' || ':x:') }}

            ${{ format('- {0} Terraform Validate', steps.validate.outcome == 'success' && ':white_check_mark:' || ':x:') }}

            ${{ format('- {0} Terraform Apply', steps.apply.outcome == 'success' && ':white_check_mark:' || ':x:') }}

            ${{ format('- {0} Run k6 Smoke Test', steps.run-smoke-test.outcome == 'success' && ':white_check_mark:' || ':x:') }}

            ${{ github.event.client_payload.slash_command.args.named.destroy != 'false' && format('- {0} Terraform Destroy', steps.destroy.outcome == 'success' && ':white_check_mark:' || ':x:') || '' }}

  aws_active_active_rhel7_proxy:
    name: Run tf-test on AWS Active-Active RHEL7 Proxy
    if: ${{ contains(github.event.client_payload.slash_command.args.unnamed.all, 'all') || contains(github.event.client_payload.slash_command.args.unnamed.all, 'aws-active-active-rhel7-proxy') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    env:
      WORK_DIR_PATH: ./tests/aws-active-active-rhel7-proxy
      K6_WORK_DIR_PATH: ./tests/tfe-load-test
      AWS_DEFAULT_REGION: us-east-2
    steps:
      - name: Create URL to the run output
        id: vars
        run: echo ::set-output name=run-url::https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID

      # Checkout the branch of the AWS TFE module to be used to test changes
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ${{ env.WORK_DIR_PATH }}
          repository: hashicorp/terraform-aws-terraform-enterprise

      - name: Set Terraform Backend to TFC Workspace
        working-directory: ${{ env.WORK_DIR_PATH }}
        run: |
          sed --in-place 's/terraform {/terraform {\n\
            backend "remote" {\n\
              organization = "terraform-enterprise-modules-test"\n\
              workspaces {\n\
                name = "aws-active-active-rhel7-proxy"\n\
              }\n\
            }\n/' versions.tf

      - name: Set Terraform Utility Module Sources
        working-directory: ${{ env.WORK_DIR_PATH }}
        env:
          SHA: ${{ github.event.client_payload.pull_request.head.sha }}
        run: |
          sed --in-place "s/?ref=main/?ref=$SHA/" main.tf
          sed --in-place "s/?ref=main/?ref=$SHA/" fixtures/test_proxy/main.tf

      # Checkout the hashicorp/tfe-load-test repository
      - name: Checkout TFE Load Test
        uses: actions/checkout@v2
        with:
          path: ${{ env.K6_WORK_DIR_PATH }}
          repository: hashicorp/tfe-load-test
          token: ${{ secrets.GH_TFE_LOAD_TEST_TOKEN }}
          persist-credentials: false

      - name: Install required tools
        working-directory: ${{ env.K6_WORK_DIR_PATH }}
        env:
          K6_URL: https://github.com/loadimpact/k6/releases/download/v0.31.1/k6-v0.31.1-linux64.tar.gz
        run: |
          sudo apt-get install jq
          curl -L $K6_URL | tar -xz --strip-components=1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_hostname: 'app.terraform.io'
          cli_config_credentials_token: ${{ secrets.AWS_ACTIVE_ACTIVE_RHEL7_PROXY_TFC_TOKEN }}
          terraform_version: 1.1.5
          terraform_wrapper: true

      # Run Terraform commands between these comments vvv

      - name: Terraform Init
        id: init
        working-directory: ${{ env.WORK_DIR_PATH }}
        run: terraform init -input=false -no-color

      - name: Terraform Validate
        id: validate
        working-directory: ${{ env.WORK_DIR_PATH }}
        run: terraform validate -no-color

      - name: Write GitHub Actions runner CIDR to Terraform Variables
        working-directory: ${{ env.WORK_DIR_PATH }}
        run: |
          echo "iact_subnet_list = [\"$( dig +short @resolver1.opendns.com myip.opendns.com )/32\"]" > github.auto.tfvars

      - name: Terraform Apply
        id: apply
        working-directory: ${{ env.WORK_DIR_PATH }}
        run: terraform apply -auto-approve -input=false -no-color

      - name: Retrieve Health Check URL
        id: retrieve-health-check-url
        working-directory: ${{ env.WORK_DIR_PATH }}
        run: |
          terraform output -no-color -raw ptfe_health_check

      - name: Wait For TFE
        id: wait-for-tfe
        timeout-minutes: 15
        env:
          HEALTH_CHECK_URL: ${{ steps.retrieve-health-check-url.outputs.stdout }}
        run: |
          echo "Curling \`health_check_url\` for a return status of 200..."
          while ! curl -sfS --max-time 5 "$HEALTH_CHECK_URL"; do sleep 5; done

      - name: Retrieve TFE URL
        id: retrieve-tfe-url
        working-directory: ${{ env.WORK_DIR_PATH }}
        run: |
          terraform output -no-color -raw ptfe_endpoint

      - name: Retrieve IACT
        id: retrieve-iact
        env:
          IACT_URL: "${{ steps.retrieve-tfe-url.outputs.stdout }}/admin/retrieve-iact"
        run: |
          token=$(curl --fail --retry 5 --verbose "$IACT_URL")
          echo "::set-output name=token::$token"

      - name: Create Admin in TFE
        id: create-admin
        env:
          TFE_PASSWORD: ${{ secrets.TFE_PASSWORD }}
          IAU_URL: "${{ steps.retrieve-tfe-url.outputs.stdout }}/admin/initial-admin-user"
          IACT: ${{ steps.retrieve-iact.outputs.token }}
        run: |
          echo \
            '{"username": "test", "email": "team-tf-enterprise@hashicorp.com", "password": "$TFE_PASSWORD"}' \
            > ./payload.json
          response=$( \
            curl \
            --fail \
            --retry 5 \
            --verbose \
            --header 'Content-Type: application/json' \
            --data @./payload.json \
            "$IAU_URL"?token="$IACT")
          echo "::set-output name=response::$response"

      - name: Retrieve Admin Token
        id: retrieve-admin-token
        env:
          RESPONSE: ${{ steps.create-admin.outputs.response }}
        run: |
          token=$(echo "$RESPONSE" | jq --raw-output '.token')
          echo "::set-output name=token::$token"

      - name: Run k6 Smoke Test
        id: run-smoke-test
        working-directory: ${{ env.K6_WORK_DIR_PATH }}
        env:
          K6_PATHNAME: "./k6"
          TFE_URL: "${{ steps.retrieve-tfe-url.outputs.stdout }}"
          TFE_API_TOKEN: "${{ steps.retrieve-admin-token.outputs.token }}"
          TFE_EMAIL: team-tf-enterprise@hashicorp.com
        run: |
          make smoke-test

      - name: Terraform Destroy
        id: destroy
        if: ${{ always() && github.event.client_payload.slash_command.args.named.destroy != 'false' }}
        working-directory: ${{ env.WORK_DIR_PATH }}
        run: terraform destroy -auto-approve -input=false -no-color

      # Run Terraform commands between these comments ^^^

      - name: Update comment
        if: ${{ always() }}
        uses: peter-evans/create-or-update-comment@c9fcb64660bc90ec1cc535646af190c992007c32
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          body: |
            ${{ format('### {0} Terraform AWS Active-Active RHEL7 Proxy Test Report', job.status == 'success' && ':white_check_mark:' || ':x:') }}

            ${{ format(':link: [Action Summary Page]({0})', steps.vars.outputs.run-url) }}

            ${{ format('- {0} Terraform Init', steps.init.outcome == 'success' && ':white_check_mark:' || ':x:') }}

            ${{ format('- {0} Terraform Validate', steps.validate.outcome == 'success' && ':white_check_mark:' || ':x:') }}

            ${{ format('- {0} Terraform Apply', steps.apply.outcome == 'success' && ':white_check_mark:' || ':x:') }}

            ${{ format('- {0} Run k6 Smoke Test', steps.run-smoke-test.outcome == 'success' && ':white_check_mark:' || ':x:') }}

            ${{ github.event.client_payload.slash_command.args.named.destroy != 'false' && format('- {0} Terraform Destroy', steps.destroy.outcome == 'success' && ':white_check_mark:' || ':x:') || '' }}